-- Schéma initial - Inventaire RISC
-- À exécuter dans Supabase : SQL Editor > New query > coller > Run

-- =========================================================
-- 1. Rôles utilisateurs (Admin / Lecture)
-- =========================================================

create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  role text not null default 'lecture' check (role in ('admin', 'lecture')),
  created_at timestamptz not null default now()
);

-- Crée automatiquement un profil (rôle "lecture" par défaut) à la création d'un compte.
-- Pour promouvoir un compte en admin : update profiles set role = 'admin' where email = '...';
-- "set search_path" est nécessaire : dans le contexte du trigger sur
-- auth.users, le chemin de résolution par défaut ne contient pas forcément
-- "public", ce qui ferait échouer silencieusement l'insertion (Supabase
-- masque alors l'erreur réelle derrière "Database error creating new user").
create or replace function handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email) values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

create or replace function is_admin()
returns boolean as $$
  select exists (
    select 1 from public.profiles where id = auth.uid() and role = 'admin'
  );
$$ language sql security definer stable set search_path = public;

alter table profiles enable row level security;

-- Visible aux seuls comptes connectés (jamais au public en lecture seule) :
-- permet d'afficher qui a créé/modifié un item parmi les admins.
create policy "profiles_select_authenticated" on profiles
  for select using (auth.role() = 'authenticated');

create policy "profiles_update_own_role_locked" on profiles
  for update using (id = auth.uid())
  with check (id = auth.uid() and role = (select role from profiles where id = auth.uid()));

-- =========================================================
-- 2. Matériel (remplace les feuilles Inventaire / Stock / Déclassé-Disparu)
-- =========================================================

create table if not exists items (
  -- "by default" (et non "always") : permet d'importer les ID RISC historiques
  -- tels quels lors de la migration. Une fois l'import terminé, exécuter :
  --   select setval('items_id_seq', (select max(id) from items));
  -- pour que les prochains items créés depuis l'appli continuent la séquence.
  id bigint generated by default as identity (start with 4744) primary key,
  type text not null,
  is_textile boolean,
  brand text,
  model text,
  textile_length_m numeric,
  specifics text,                 -- "Remarques & spécificité"
  manufacturer_serial text,
  manufacture_date date,
  manufacture_date_unknown boolean not null default false,  -- date d'origine jugée aberrante à la migration
  decommission_date date,
  status text not null default 'en_service'
    check (status in ('stock', 'en_service', 'declasse', 'disparu')),
  rope_color text,                -- uniquement pertinent pour type = 'Corde'
  rope_rotation text,             -- ex: "stock tampon", notes de rotation
  remarks text,
  legacy_notes text,              -- import brut des colonnes "Remarques"/"Alerte" texte libre historiques
  created_by uuid references profiles(id),
  updated_by uuid references profiles(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists items_status_idx on items (status);
create index if not exists items_type_idx on items (type);

create or replace function set_updated_at()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

drop trigger if exists items_set_updated_at on items;
create trigger items_set_updated_at
  before update on items
  for each row execute function set_updated_at();

-- Traçabilité : qui a créé/modifié un item.
create or replace function set_items_audit()
returns trigger as $$
begin
  if TG_OP = 'INSERT' then
    new.created_by := auth.uid();
    new.updated_by := auth.uid();
  elsif TG_OP = 'UPDATE' then
    new.updated_by := auth.uid();
    new.created_by := old.created_by; -- ne change jamais après la création
  end if;
  return new;
end;
$$ language plpgsql security definer set search_path = public;

drop trigger if exists items_set_audit on items;
create trigger items_set_audit
  before insert or update on items
  for each row execute function set_items_audit();

-- Utilisé une seule fois par le script scripts/import-excel.ts après la migration,
-- pour que la séquence d'auto-incrémentation reparte après le plus grand ID RISC importé.
create or replace function set_items_id_seq(new_value bigint)
returns void as $$
begin
  perform setval('public.items_id_seq', new_value);
end;
$$ language plpgsql security definer set search_path = public;

-- Réservée au script d'import (exécuté avec la clé service_role, qui contourne
-- de toute façon ces droits) : personne d'autre ne doit pouvoir l'appeler.
revoke all on function set_items_id_seq(bigint) from public, anon, authenticated;

alter table items enable row level security;

create policy "items_select_all" on items for select using (true);
create policy "items_insert_admin" on items for insert with check (is_admin());
create policy "items_update_admin" on items for update using (is_admin());
create policy "items_delete_admin" on items for delete using (is_admin());

-- =========================================================
-- 3. Historique des contrôles SECT (remplace les colonnes annuelles)
-- =========================================================

create table if not exists inspections (
  id bigint generated always as identity primary key,
  item_id bigint not null references items(id) on delete cascade,
  inspected_on date not null,
  result text,             -- ex: "OK", "NON CONTRÔLÉ", etc.
  notes text,
  created_by uuid references profiles(id),
  created_at timestamptz not null default now()
);

create index if not exists inspections_item_idx on inspections (item_id, inspected_on desc);

alter table inspections enable row level security;

create policy "inspections_select_all" on inspections for select using (true);
create policy "inspections_insert_admin" on inspections for insert with check (is_admin());
create policy "inspections_update_admin" on inspections for update using (is_admin());
create policy "inspections_delete_admin" on inspections for delete using (is_admin());

-- =========================================================
-- 4. Vue avec alertes calculées
--    Règle : âge > 10 ans OU dernier contrôle > 1 an, ET statut = en_service
-- =========================================================

create or replace view items_with_alerts as
select
  i.*,
  li.last_inspection_on,
  (
    i.status = 'en_service'
    and i.manufacture_date_unknown = false
    and i.manufacture_date is not null
    and i.manufacture_date <= (current_date - interval '10 years')
  ) as alert_age,
  (
    i.status = 'en_service'
    and (li.last_inspection_on is null or li.last_inspection_on <= (current_date - interval '1 year'))
  ) as alert_control
from items i
left join lateral (
  select max(inspected_on) as last_inspection_on
  from inspections
  where inspections.item_id = i.id
) li on true;
